name: Auth Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-auth-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      NODE_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Start Next.js server
        run: npm run start &

      - name: Wait for server to be ready
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:3000/ >/dev/null; then
              echo "Server is up"; exit 0;
            fi
            echo "Waiting for server..."; sleep 2;
          done
          echo "Server did not start in time"; exit 1

      - name: Run auth test script
        run: node scripts/auth-test.mjs